global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'l1-team'
  routes:
    - match:
        severity: critical
      receiver: 'l2-team'

receivers:
- name: 'l1-team'
  email_configs:
  - to: 'l1@company.com'
    from: 'alertmanager@company.com'
    smarthost: 'smtp.example.com:25'
    require_tls: false

- name: 'l2-team'
  email_configs:
  - to: 'l2@company.com'
    from: 'alertmanager@company.com'
    smarthost: 'smtp.example.com:25'
    require_tls: false
